# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: run_hx

on:
  schedule:
    # 设置启动时间，为 UTC 时间, UTC23点 对应北京时间早7点
    - cron : '0 0 * * *'
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        required: true
        default: '邮箱'
permissions:
  contents: write
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  build:

    runs-on: macos-latest
    env:
      TZ: Asia/Shanghai
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run python code
      run: python hx/hx.py "${{ github.event.inputs.name }}"
      env:
        APP_ID: ${{ secrets.APP_ID }}
        ydyp: ${{ secrets.ydyp }}
    # - name: commit files
    #   run: |
    #       git config --local user.email "action@github.com"
    #       git config --local user.name "GitHub Action"
    #       git add -A
    #       git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
    - name: Commit hx folder files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        # 只添加 hx 文件夹里的内容
        git add hx/
        # 如果有变化就提交
        git diff-index --quiet HEAD || git commit -m "update hx folder files"
          
    - name: push changes
      uses: ad-m/github-push-action@v0.8.0
      with:
          github_token: ${{ secrets.TOKEN }}
          branch: main 
